/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCasa;
import ec.edu.ups.controlador.ControladorPersona;
import ec.edu.ups.modelo.Casa;
import ec.edu.ups.modelo.Persona;
import ec.edu.ups.utils.JPAUtils;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres
 */
public class VentanaCompra extends javax.swing.JFrame {
private ControladorCasa controladorCasa;
private Casa casa;
private Persona persona;
private ControladorPersona controladorPersona;
private String direccionCasa;
private String precio;
private String iDBusqueda,cedula,nombre,apellido,direccion,fechaN,salario;
private Long busqueda,Id;
private Double s;
private VentanaRegistroCliente ventanaRegistroCliente;
    /**
     * Creates new form VentanaCompra
     */
    public VentanaCompra() {
        initComponents();
        controladorCasa= new ControladorCasa();
        controladorPersona=new ControladorPersona();
        casa = new Casa();
        persona = new Persona();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaPersona = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaCasa = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jTablaPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cedula", "Nombre", "Apellido", "Fecha de Nacimiento", "Direccion", "Salario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaPersonaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaPersona);

        jTablaCasa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Direccion", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaCasaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablaCasa);

        jButton1.setText("Comprar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        jLabel2.setText("Casa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 53, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(419, 419, 419))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(428, 428, 428))))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
cargarDatosCasa();
cargarDatosPersona();
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(salario);
        s=Double.parseDouble(salario);
     
busqueda=Long.parseLong(iDBusqueda);
        System.out.println(busqueda);
        Persona persona1=new Persona(busqueda, cedula, nombre, apellido, fechaN, direccion, s); 
        List<Casa> casas = new ArrayList();
Double precioC =Double.parseDouble(precio);
casas.add(new Casa(Id,direccionCasa,precioC,persona1));
persona1.setLsitaCasa(casas);
        System.out.println(casas);
    try {
        controladorPersona.actualizar(persona1);
    } catch (Exception ex) {
        Logger.getLogger(VentanaCompra.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTablaPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaPersonaMouseClicked
      int fila =jTablaCasa.getSelectedRow(); 
      if (fila >= 0) {
           iDBusqueda = jTablaPersona.getValueAt(fila, 0).toString();
            cedula = jTablaPersona.getValueAt(fila, 1).toString();
            nombre = jTablaPersona.getValueAt(fila, 2).toString();
            apellido = jTablaPersona.getValueAt(fila, 3).toString();
            fechaN = jTablaPersona.getValueAt(fila, 4).toString();
            direccion = jTablaPersona.getValueAt(fila, 5).toString();
            salario = jTablaPersona.getValueAt(fila, 6).toString();
            System.out.println(iDBusqueda+cedula+nombre+apellido+fechaN+direccion+salario);
           }
    }//GEN-LAST:event_jTablaPersonaMouseClicked

    private void jTablaCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaCasaMouseClicked
           int fila =jTablaCasa.getSelectedRow();
           if (fila >= 0) {
          String Ids= jTablaCasa.getValueAt(fila, 0).toString();
          Id=Long.parseLong(Ids);
           direccionCasa = jTablaCasa.getValueAt(fila, 1).toString();
           precio = jTablaCasa.getValueAt(fila, 2).toString();
           
           }
    }//GEN-LAST:event_jTablaCasaMouseClicked
public void cargarDatosCasa(){
    DefaultTableModel modelo = (DefaultTableModel) jTablaCasa.getModel();
    modelo.setRowCount(0); 
    controladorCasa.buscarTodo();
    for (Casa casa1 : controladorCasa.buscarTodo()) {
        Object[] rowData = {casa1.getId(),casa1.getDireccion(), casa1.getPrecio()};
           modelo.addRow(rowData);
    }
    
        jTablaCasa.setModel(modelo);
       
}
public void cargarDatosPersona(){
DefaultTableModel modelo = (DefaultTableModel) jTablaPersona.getModel();
    modelo.setRowCount(0); 
    controladorPersona.buscarTodo();
    for (Persona persona1 : controladorPersona.buscarTodo()) {
        Object[] rowData = {persona1.getId(),persona1.getCedula(),persona1.getNombre(),persona1.getApellido(),persona1.getFechaNacimiento(),persona1.getDireccion(),persona1.getSalario()};
           modelo.addRow(rowData);
    }
    
        jTablaPersona.setModel(modelo);
       
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaCasa;
    private javax.swing.JTable jTablaPersona;
    // End of variables declaration//GEN-END:variables
}
